malagu:
  webpack:
    config:
      devtool: false
    workboxWebpackPlugin:
      maximumFileSizeToCacheInBytes: 5242880
    filterWarningsPlugin:
        cellbang: [ get-caller-file ]
  faas-adapter:
    service:
      name: cellbang
      vpcConfig:
        vpcId: vpc-bp141rytvrwceloi1rzow
        vSwitchIds: [ vsw-bp198naxot8mpp6ak9hnq ]
        securityGroupId: sg-bp1gdn0p8291qxmpeo2z
      logConfig: 
        logstore: logstore
        project: cellbang
      role: acs:ram::${malagu['faas-adapter'].account.id}:role/cellbangrole
    function:
      memorySize: 1024
      instanceConcurrency: 100
    customDomain:
      name: ${pkg.name}.cellbang.com
      protocol: HTTP,HTTPS
      certConfig:
        certName: cellbang
        certificate: "${ env.SSL_PEM ?: '../../ssl/cert.pem' }"
        privateKey: "${ env.SSL_KEY ?: '../../ssl/cert.key' }"
