mode: [ secret ]
malagu:
  name: ${pkg.description || pkg.name}
  rpc:
    merge:
      enabled: true
  webpack:
    config:
      devServer:
        watchOptions: 
          aggregateTimeout: 1500
          ignored: [ '**/*.ts' ]